#!/usr/bin/env python3
# SPDX-License-Identifier: proprietary
"""Emit dist/ifs08_can_ids.h -- a C header every firmware repo can
include to share frame IDs / DLCs / enum values without redefining
them locally (and drifting from this single source of truth).

dist/ is NOT committed -- firmware CMake runs this at configure time.

Usage:
  python3 -m tools.gen_c_header           # write dist/ifs08_can_ids.h
  python3 -m tools.gen_c_header --out <dir>
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from typing import List, Optional

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from spec import ams, vcu, udv                       # noqa: E402
from spec.common import Message, Signal              # noqa: E402


ALL_MESSAGES = [
    ("AMS", ams.MESSAGES),
    ("VCU", vcu.MESSAGES),
    ("UDV", udv.MESSAGES),
]


HEADER_PROLOGUE = '''\
/* SPDX-License-Identifier: proprietary */
/*
 * IFS08 CAN frame IDs / DLCs / enum values.
 *
 * GENERATED by isc-fs/ifs08-can-spec  --  do not hand-edit.
 * Source of truth: spec/{ams,vcu,udv}.py in that repo.
 *
 * Include from per-ECU firmware so all sides agree on the same frame
 * IDs without redefining them locally:
 *
 *     #include "ifs08_can_ids.h"
 *     if (frame.id == IFS08_AMS_AMS_status_ID) { ... }
 *
 * Naming: IFS08_<sender>_<message_name>_ID / _DLC.
 */
#ifndef IFS08_CAN_IDS_H_
#define IFS08_CAN_IDS_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

'''

HEADER_EPILOGUE = '''
#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif  /* IFS08_CAN_IDS_H_ */
'''


def emit_header() -> str:
    lines: List[str] = [HEADER_PROLOGUE]

    # Frame IDs + DLCs per ECU.
    for owner, msgs in ALL_MESSAGES:
        if not msgs:
            continue
        lines.append(f"/* ---- {owner} ---- */\n")
        for m in msgs:
            base = f"IFS08_{m.sender}_{m.name}"
            lines.append(
                f"#define {base}_ID   0x{m.can_id:03X}u  /* {m.comment[:60]} */"
                if m.comment else
                f"#define {base}_ID   0x{m.can_id:03X}u"
            )
            lines.append(f"#define {base}_DLC  {m.dlc}u")
        lines.append("")

    # Enum tables (VAL_ in DBC).
    have_enum = False
    for owner, msgs in ALL_MESSAGES:
        for m in msgs:
            for s in m.signals:
                if not s.enum:
                    continue
                if not have_enum:
                    lines.append("/* ---- enum values ---- */\n")
                    have_enum = True
                base = f"IFS08_{m.sender}_{m.name}_{s.name}".upper()
                for k, v in sorted(s.enum.items()):
                    safe = v.replace(" ", "_").upper()
                    lines.append(f"#define {base}_{safe}   {k}u")
                lines.append("")

    lines.append(HEADER_EPILOGUE)
    return "".join(l if l.endswith("\n") else l + "\n" for l in lines)


# --- CLI -------------------------------------------------------------------

def _default_out_dir() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parents[1] / "dist"


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path, default=_default_out_dir(),
                    help="output directory (default: <repo>/dist/)")
    args = ap.parse_args(argv)

    args.out.mkdir(parents=True, exist_ok=True)
    path = args.out / "ifs08_can_ids.h"
    path.write_text(emit_header())
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
