#!/usr/bin/env python3
# SPDX-License-Identifier: proprietary
"""Emit dist/ifs08_can_codecs.hpp -- typed C++17 struct + symmetric
encode/decode pair per Message.

dist/ is NOT committed -- firmware CMake regenerates at configure time.

Why this exists
---------------
Hand-rolled encoders + hand-rolled decoders on opposite sides of the
bus drift. We've burned cycles on at least two flavours of that bug:

  - #234: encoder packed a 16-bit BE value at byte 4 but the decoder
    read it as LE -- byte-swapped current readings for two weeks.
  - #243: a DLC mismatch where the TX side wrote 7 bytes but the RX
    decoder read 8, so the last byte was always whatever stuck in the
    SRAM mailbox from a previous frame.

If both sides #include the same generated codec header, that whole
class of bug is impossible by construction. The struct is the source
of truth; encode/decode are byte-exact inverses (asserted by the
roundtrip smoke test in CI).

Usage:
  python3 -m tools.gen_cpp_codec           # write dist/ifs08_can_codecs.hpp
  python3 -m tools.gen_cpp_codec --out <dir>
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys
from typing import List, Optional, Tuple

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from spec import ams, vcu, udv                       # noqa: E402
from spec.common import Message, Signal              # noqa: E402


ALL_MESSAGES = [
    ("AMS", ams.MESSAGES),
    ("VCU", vcu.MESSAGES),
    ("UDV", udv.MESSAGES),
]


PROLOGUE = r'''/* SPDX-License-Identifier: proprietary */
/*
 * IFS08 CAN typed codecs (C++17).
 *
 * GENERATED by isc-fs/IFS08-DBCinator  --  do not hand-edit.
 * Source of truth: spec/{ams,vcu,udv}.py in that repo.
 *
 * For every Message we emit:
 *   struct <Sender>_<Msg>_t { ... };
 *   bool decode_<Sender>_<Msg>(const uint8_t (&data)[8], <Sender>_<Msg>_t& out);
 *   bool encode_<Sender>_<Msg>(const <Sender>_<Msg>_t& in, uint8_t (&data)[8]);
 *
 * Both sides of the bus #include this header. Asymmetry between
 * encode/decode (the #234/#243 bug class) is impossible by
 * construction: they're generated from the same Signal list.
 */
#ifndef IFS08_CAN_CODECS_HPP_
#define IFS08_CAN_CODECS_HPP_

#include <cstdint>
#include <cmath>

namespace ifs08 {
namespace can {
namespace detail {

// ---- Bit-level pack/unpack ------------------------------------------------
//
// LE (Intel): bit i of the value lives at frame bit (start_bit + i).
// BE (Motorola Forward MSB, DBC convention): MSB of the value lives at
// frame bit start_bit (where start_bit = 8*byte + 7 for byte-aligned
// fields). Bits descend within a byte (towards bit 0), then jump to
// bit 7 of the next byte. Equivalent to:
//
//     bit = start;
//     for i in 0..len-1:
//         emit / consume frame bit `bit`
//         if (bit & 7) == 0: bit += 15      // jump to MSB of next byte
//         else:              bit -= 1

inline uint64_t get_bits_le(const uint8_t (&d)[8], unsigned start, unsigned len) noexcept {
    uint64_t v = 0;
    for (unsigned i = 0; i < len; ++i) {
        const unsigned bit = start + i;
        v |= static_cast<uint64_t>((d[bit >> 3] >> (bit & 7)) & 1u) << i;
    }
    return v;
}

inline void set_bits_le(uint8_t (&d)[8], unsigned start, unsigned len, uint64_t v) noexcept {
    for (unsigned i = 0; i < len; ++i) {
        const unsigned bit = start + i;
        const uint8_t b = static_cast<uint8_t>((v >> i) & 1u);
        d[bit >> 3] = static_cast<uint8_t>((d[bit >> 3] & ~(1u << (bit & 7))) | (b << (bit & 7)));
    }
}

inline uint64_t get_bits_be(const uint8_t (&d)[8], unsigned start, unsigned len) noexcept {
    uint64_t v = 0;
    unsigned bit = start;
    for (unsigned i = 0; i < len; ++i) {
        const uint64_t b = (d[bit >> 3] >> (bit & 7)) & 1u;
        v = (v << 1) | b;
        if ((bit & 7) == 0) bit += 15;
        else                bit -= 1;
    }
    return v;
}

inline void set_bits_be(uint8_t (&d)[8], unsigned start, unsigned len, uint64_t v) noexcept {
    unsigned bit = start;
    for (unsigned i = 0; i < len; ++i) {
        const uint8_t b = static_cast<uint8_t>((v >> (len - 1 - i)) & 1u);
        d[bit >> 3] = static_cast<uint8_t>((d[bit >> 3] & ~(1u << (bit & 7))) | (b << (bit & 7)));
        if ((bit & 7) == 0) bit += 15;
        else                bit -= 1;
    }
}

inline int64_t sign_extend(uint64_t v, unsigned len) noexcept {
    const uint64_t m = 1ull << (len - 1);
    return static_cast<int64_t>((v ^ m) - m);
}

} // namespace detail

'''

EPILOGUE = '''
} // namespace can
} // namespace ifs08

#endif  // IFS08_CAN_CODECS_HPP_
'''


# --------------------------------------------------------------------------

_BAD_CHAR = re.compile(r"[^A-Za-z0-9_]")


def _ident(name: str) -> str:
    """Make a C++ identifier out of a spec name."""
    out = _BAD_CHAR.sub("_", name)
    if out and out[0].isdigit():
        out = "_" + out
    return out


def _is_physical(sig: Signal) -> bool:
    """True iff the signal has a scale/offset that means it's not a raw int."""
    return sig.factor != 1.0 or sig.offset != 0.0


def _int_type(length: int, signed: bool) -> str:
    """Smallest stdint type that fits `length` bits."""
    for cap, u, s in [(8, "uint8_t", "int8_t"),
                      (16, "uint16_t", "int16_t"),
                      (32, "uint32_t", "int32_t"),
                      (64, "uint64_t", "int64_t")]:
        if length <= cap:
            return s if signed else u
    raise ValueError(f"signal too wide: {length} bits")


def _field_type(sig: Signal) -> str:
    if _is_physical(sig):
        return "float"
    return _int_type(sig.field.length, sig.field.sign == "-")


def _decode_expr(sig: Signal) -> str:
    """C++ expression that materialises the typed value from `raw`."""
    length = sig.field.length
    signed = sig.field.sign == "-"
    if signed:
        raw_expr = f"detail::sign_extend(raw, {length})"
    else:
        raw_expr = "raw"
    if _is_physical(sig):
        return (f"static_cast<float>({raw_expr}) * "
                f"{sig.factor!r}f + {sig.offset!r}f")
    return f"static_cast<{_field_type(sig)}>({raw_expr})"


def _encode_expr(sig: Signal, field_ref: str) -> str:
    """C++ expression that turns a typed field into the raw bit pattern."""
    length = sig.field.length
    signed = sig.field.sign == "-"
    mask = (1 << length) - 1
    if _is_physical(sig):
        # Round-to-nearest with banker-safe lrintf.
        scaled = (f"std::lrintf(({field_ref} - {sig.offset!r}f) / {sig.factor!r}f)")
        return f"static_cast<uint64_t>({scaled}) & 0x{mask:X}ull"
    return f"static_cast<uint64_t>({field_ref}) & 0x{mask:X}ull"


def _get_bits_call(sig: Signal) -> str:
    fn = "get_bits_be" if sig.field.byte_order == "0" else "get_bits_le"
    return f"detail::{fn}(data, {sig.field.start_bit}, {sig.field.length})"


def _set_bits_call(sig: Signal, raw_expr: str) -> str:
    fn = "set_bits_be" if sig.field.byte_order == "0" else "set_bits_le"
    return f"detail::{fn}(data, {sig.field.start_bit}, {sig.field.length}, {raw_expr})"


def emit_message(msg: Message) -> str:
    """Emit struct + decode + encode for one Message."""
    struct_name = f"{msg.sender}_{_ident(msg.name)}_t"
    decode_name = f"decode_{msg.sender}_{_ident(msg.name)}"
    encode_name = f"encode_{msg.sender}_{_ident(msg.name)}"

    lines: List[str] = []
    lines.append(f"// ---- 0x{msg.can_id:03X}  {msg.name}  "
                 f"(sender={msg.sender}, dlc={msg.dlc}) ----")
    if msg.comment:
        for ln in msg.comment.splitlines():
            lines.append(f"// {ln}")

    # struct
    lines.append(f"struct {struct_name} {{")
    for sig in msg.signals:
        ty = _field_type(sig)
        comment = ""
        bits = []
        if sig.unit:
            bits.append(sig.unit)
        if _is_physical(sig):
            bits.append(f"factor={sig.factor}, offset={sig.offset}")
        if bits:
            comment = "  // " + ", ".join(bits)
        lines.append(f"    {ty} {_ident(sig.name)}{{}};{comment}")
    lines.append("};")
    lines.append("")

    # decode
    lines.append(f"inline bool {decode_name}(const uint8_t (&data)[8], "
                 f"{struct_name}& out) noexcept {{")
    lines.append("    uint64_t raw;")
    for sig in msg.signals:
        lines.append(f"    raw = {_get_bits_call(sig)};")
        lines.append(f"    out.{_ident(sig.name)} = {_decode_expr(sig)};")
    lines.append("    return true;")
    lines.append("}")
    lines.append("")

    # encode
    lines.append(f"inline bool {encode_name}(const {struct_name}& in, "
                 f"uint8_t (&data)[8]) noexcept {{")
    lines.append("    for (auto& b : data) b = 0;")
    for sig in msg.signals:
        raw = _encode_expr(sig, f"in.{_ident(sig.name)}")
        lines.append(f"    {_set_bits_call(sig, raw)};")
    lines.append("    return true;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines) + "\n"


def _sample_raw(length: int, signed: bool, seed: int) -> int:
    """Deterministic raw bit pattern fitting in `length` bits.

    Sign-extended if `signed`. Used by the roundtrip test as the
    canonical value for each field; chosen by hashing the field name +
    a per-message seed so we don't just probe zeros.
    """
    # Truncate to length bits.
    mask = (1 << length) - 1
    raw = (seed * 0x9E3779B1) & 0xFFFFFFFF
    raw &= mask
    if length == 1:
        return raw & 1
    if signed:
        # Sign-extend.
        sign_bit = 1 << (length - 1)
        if raw & sign_bit:
            raw -= (1 << length)
    return raw


def emit_roundtrip_test() -> str:
    """Emit a stand-alone .cpp that encodes-then-decodes every message
    and asserts struct equality. Linked + run in CI."""

    lines: List[str] = []
    lines.append("/* SPDX-License-Identifier: proprietary */")
    lines.append("/* GENERATED by tools/gen_cpp_codec.py -- do not hand-edit. */")
    lines.append("/*")
    lines.append(" * Encode-then-decode every Message struct, assert equality.")
    lines.append(" * If encode/decode ever fall out of sync, this fails.")
    lines.append(" */")
    lines.append('#include "ifs08_can_codecs.hpp"')
    lines.append("#include <cstdio>")
    lines.append("#include <cmath>")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("static int g_fails = 0;")
    lines.append("")
    lines.append("template <typename T>")
    lines.append("static bool eq_int(T a, T b, const char* msg, const char* field) {")
    lines.append("    if (a == b) return true;")
    lines.append("    std::fprintf(stderr, \"FAIL %s.%s: encoded %lld decoded %lld\\n\",")
    lines.append("                 msg, field, (long long)a, (long long)b);")
    lines.append("    ++g_fails; return false;")
    lines.append("}")
    lines.append("")
    lines.append("static bool eq_float(float a, float b, float tol, const char* msg, const char* field) {")
    lines.append("    if (std::fabs(a - b) <= tol) return true;")
    lines.append("    std::fprintf(stderr, \"FAIL %s.%s: encoded %.6f decoded %.6f tol %.6f\\n\",")
    lines.append("                 msg, field, a, b, tol);")
    lines.append("    ++g_fails; return false;")
    lines.append("}")
    lines.append("")

    seed = 1
    for owner, msgs in ALL_MESSAGES:
        for m in msgs:
            seed += 1
            struct_name = f"{m.sender}_{_ident(m.name)}_t"
            test_fn = f"test_{m.sender}_{_ident(m.name)}"
            lines.append(f"static void {test_fn}() {{")
            lines.append(f"    using namespace ifs08::can;")
            lines.append(f"    {struct_name} a{{}};")

            for i, sig in enumerate(m.signals):
                length = sig.field.length
                signed = sig.field.sign == "-"
                raw = _sample_raw(length, signed, seed * 1009 + i * 31)
                fname = _ident(sig.name)
                if _is_physical(sig):
                    phys = raw * sig.factor + sig.offset
                    lines.append(f"    a.{fname} = {phys!r}f;")
                else:
                    lines.append(f"    a.{fname} = static_cast<{_field_type(sig)}>({raw});")

            lines.append(f"    uint8_t buf[8];")
            lines.append(f"    encode_{m.sender}_{_ident(m.name)}(a, buf);")
            lines.append(f"    {struct_name} b{{}};")
            lines.append(f"    decode_{m.sender}_{_ident(m.name)}(buf, b);")
            for sig in m.signals:
                fname = _ident(sig.name)
                tag = f'"{m.sender}_{m.name}"'
                if _is_physical(sig):
                    tol = abs(sig.factor) * 0.51
                    lines.append(f'    eq_float(a.{fname}, b.{fname}, {tol!r}f, {tag}, "{sig.name}");')
                else:
                    lines.append(f'    eq_int(a.{fname}, b.{fname}, {tag}, "{sig.name}");')
            lines.append("}")
            lines.append("")

    lines.append("int main(void) {")
    for owner, msgs in ALL_MESSAGES:
        for m in msgs:
            lines.append(f"    test_{m.sender}_{_ident(m.name)}();")
    lines.append("    if (g_fails) {")
    lines.append("        std::fprintf(stderr, \"%d roundtrip failures\\n\", g_fails);")
    lines.append("        return 1;")
    lines.append("    }")
    lines.append("    std::printf(\"all roundtrip checks passed\\n\");")
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_header() -> str:
    out: List[str] = [PROLOGUE]
    for owner, msgs in ALL_MESSAGES:
        if not msgs:
            continue
        out.append(f"// ============================================================\n"
                   f"// {owner}  ({len(msgs)} messages)\n"
                   f"// ============================================================\n\n")
        for m in msgs:
            out.append(emit_message(m))
    out.append(EPILOGUE)
    return "".join(out)


# --- CLI -------------------------------------------------------------------

def _default_out_dir() -> pathlib.Path:
    return pathlib.Path(__file__).resolve().parents[1] / "dist"


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=pathlib.Path, default=_default_out_dir(),
                    help="output directory (default: <repo>/dist/)")
    args = ap.parse_args(argv)

    args.out.mkdir(parents=True, exist_ok=True)
    hpath = args.out / "ifs08_can_codecs.hpp"
    hpath.write_text(emit_header())
    print(f"wrote {hpath}")
    tpath = args.out / "ifs08_can_codecs_roundtrip.cpp"
    tpath.write_text(emit_roundtrip_test())
    print(f"wrote {tpath}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
